language: python
python:
  - "3.9"

addons:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
env:
  global:
    # A different port must be used when not using the
    # default PostgreSQL:
    - PGPORT=5433

services:
  - postgresql

before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@13-main restart


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install coveralls

before_script:
  # Create the test database:
  - sudo psql -p 5433 -U postgres -c 'create database nightshift_ci_test;'

# command to run tests
script:
  - pytest --cov=nightshift/
after_success:
  - coveralls