language: python
python:
  - "3.9"

services:
  - postgresql

before_script:
  # Create the test database:
  - psql -c 'create database nightshiftTestDB;' -U postgres

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script:
  - pytest --cov=nightshift/
after_success:
  - coveralls