# safelist
branches:
  only: 
    - main
    - develop
language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=nightshift/
after_success:
  - coveralls