# -*- coding: utf-8 -*-

WSRESP = {
    "numberOfRecords": 1,
    "briefRecords": [
        {
            "oclcNumber": "1190756389",
            "title": "The saddest words : William Faulkner's Civil War",
            "creator": "Michael Edward Gorra",
            "date": "2020",
            "language": "eng",
            "generalFormat": "Book",
            "specificFormat": "Digital",
            "edition": "First edition.",
            "publisher": "Liveright Publishing Corporation",
            "catalogingInfo": {
                "catalogingAgency": "TEFOD",
                "transcribingAgency": "TEFOD",
            },
        }
    ],
}


NPRESP = {
    "data": [
        {
            "id": "22259002",
            "nyplSource": "sierra-nypl",
            "nyplType": "bib",
            "updatedDate": "2020-09-29T15:30:46-04:00",
            "createdDate": "2020-09-22T20:23:19-04:00",
            "deletedDate": None,
            "deleted": False,
            "locations": [{"code": "ia", "name": "Electronic Material for Adults"}],
            "suppressed": False,
            "lang": {"code": "eng", "name": "English"},
            "title": "The saddest words [electronic resource] : William faulkner's civil war.",
            "author": "Gorra, Michael.",
            "materialType": {"code": "z  ", "value": "E-BOOK"},
            "bibLevel": {"code": "m", "value": "MONOGRAPH"},
            "publishYear": 2020,
            "catalogDate": "2020-09-22",
            "country": {"code": "nyu", "name": "New York (State)"},
            "normTitle": "saddest words electronic resource william faulkners civil war",
            "normAuthor": "gorra michael",
            "standardNumbers": ["9781631491719"],
            "controlNumber": "ODN0005077214",
            "fixedFields": {
                "24": {"label": "Language", "value": "eng", "display": "English"},
                "25": {"label": "Skip", "value": "4", "display": None},
                "26": {
                    "label": "Location",
                    "value": "ia   ",
                    "display": "Electronic Material for Adults",
                },
                "27": {"label": "COPIES", "value": "1", "display": None},
                "28": {"label": "Cat. Date", "value": "2020-09-22", "display": None},
                "29": {"label": "Bib Level", "value": "m", "display": "MONOGRAPH"},
                "30": {"label": "Material Type", "value": "z  ", "display": "E-BOOK"},
                "31": {"label": "Bib Code 3", "value": "a", "display": None},
                "80": {"label": "Record Type", "value": "b", "display": None},
                "81": {"label": "Record Number", "value": "22259002", "display": None},
                "83": {
                    "label": "Created Date",
                    "value": "2020-09-22T20:23:19Z",
                    "display": None,
                },
                "84": {
                    "label": "Updated Date",
                    "value": "2020-09-29T15:30:46Z",
                    "display": None,
                },
                "85": {"label": "No. of Revisions", "value": "2", "display": None},
                "86": {"label": "Agency", "value": "1", "display": None},
                "89": {
                    "label": "Country",
                    "value": "nyu",
                    "display": "New York (State)",
                },
                "98": {
                    "label": "PDATE",
                    "value": "2020-09-22T20:23:19Z",
                    "display": None,
                },
                "107": {"label": "MARC Type", "value": " ", "display": None},
            },
            "varFields": [
                {
                    "fieldTag": "a",
                    "marcTag": "100",
                    "ind1": "1",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "Gorra, Michael."}],
                },
                {
                    "fieldTag": "l",
                    "marcTag": "010",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "  2017022370"}],
                },
                {
                    "fieldTag": "b",
                    "marcTag": "710",
                    "ind1": "2",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "OverDrive, Inc.,"},
                        {"tag": "e", "content": "distributor."},
                    ],
                },
                {
                    "fieldTag": "c",
                    "marcTag": "091",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "eNYPL Book"}],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "650",
                    "ind1": " ",
                    "ind2": "7",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Biography & Autobiography."},
                        {"tag": "2", "content": "OverDrive"},
                    ],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "650",
                    "ind1": " ",
                    "ind2": "7",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "History."},
                        {"tag": "2", "content": "OverDrive"},
                    ],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "650",
                    "ind1": " ",
                    "ind2": "7",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Literary Criticism."},
                        {"tag": "2", "content": "OverDrive"},
                    ],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "655",
                    "ind1": " ",
                    "ind2": "0",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "Electronic books."}],
                },
                {
                    "fieldTag": "i",
                    "marcTag": "020",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "9781631491719"},
                        {"tag": "q", "content": "(electronic bk)"},
                    ],
                },
                {
                    "fieldTag": "i",
                    "marcTag": "020",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "1631491719"},
                        {"tag": "q", "content": "(electronic bk)"},
                    ],
                },
                {
                    "fieldTag": "i",
                    "marcTag": "024",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "1111111111"},
                    ],
                },
                {
                    "fieldTag": "i",
                    "marcTag": "024",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "2222222222"},
                    ],
                },
                {
                    "fieldTag": "n",
                    "marcTag": "520",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {
                            "tag": "a",
                            "content": "How do we read William Faulkner in the twenty-first century? asks Michael Gorra, in this reconsideration of Faulkner's life and legacy. William Faulkner, one of America's most iconic writers, is an author who defies easy interpretation. Born in 1897 in Mississippi, Faulkner wrote such classic novels as Absolom, Absolom! and The Sound and The Fury, creating in Yoknapatawpha county one of the most memorable gallery of characters ever assembled in American literature. Yet, as acclaimed literary critic Michael Gorra explains, Faulkner has sustained justified criticism for his failures of racial nuance -- his ventriloquism of black characters and his rendering of race relations in a largely unreconstructed South -- demanding that we reevaluate the Nobel laureate's life and legacy in the twenty-first century, as we reexamine the junctures of race and literature in works that once rested firmly in the American canon. Interweaving biography, literary criticism, and rich travelogue, The Saddest Words argues that even despite these contradictions -- and perhaps because of them -- William Faulkner still needs to be read, and even more, remains central to understanding the contradictions inherent in the American experience itself. Evoking Faulkner's biography and his literary characters, Gorra illuminates what Faulkner maintained was \"the South's curse and its separate destiny,\" a class and racial system built on slavery that was devastated during the Civil War and was reimagined thereafter through the South's revanchism. Driven by currents of violence, a \"Lost Cause\" romanticism not only defined Faulkner's twentieth century but now even our own age. Through Gorra's critical lens, Faulkner's mythic Yoknapatawpha County comes alive as his imagined land finds itself entwined in America's history, the characters wrestling with the ghosts of a past that refuses to stay buried, stuck in an unending cycle between those two saddest words, \"was\" and \"again.\" Upending previous critical traditions, The Saddest Words returns Faulkner to his sociopolitical context, revealing the civil war within him and proving that \"the real war lies not only in the physical combat, but also in the war after the war, the war over its memory and meaning.\" Filled with vignettes of Civil War battles and generals, vivid scenes from Gorra's travels through the South -- including Faulkner's Oxford, Mississippi -- and commentaries on Faulkner's fiction, The Saddest Words is a mesmerizing work of literary thought that recontextualizes Faulkner in light of the most plangent cultural issues facing America today.",
                        }
                    ],
                },
                {
                    "fieldTag": "n",
                    "marcTag": "533",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Electronic reproduction."},
                        {"tag": "b", "content": "New York :"},
                        {"tag": "c", "content": "Liveright,"},
                        {"tag": "d", "content": "2020."},
                        {
                            "tag": "n",
                            "content": "Requires OverDrive Read (file size: N/A KB) or Adobe Digital Editions (file size: 4694 KB) or Kobo app or compatible Kobo device (file size: N/A KB) or Amazon Kindle (file size: N/A KB).",
                        },
                    ],
                },
                {
                    "fieldTag": "o",
                    "marcTag": "001",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "ODN0005077214",
                    "subfields": None,
                },
                {
                    "fieldTag": "p",
                    "marcTag": "260",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "c", "content": "2020."}],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "300",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "1 online resource"}],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "336",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "text"},
                        {"tag": "b", "content": "txt"},
                        {"tag": "2", "content": "rdacontent"},
                    ],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "337",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "computer"},
                        {"tag": "b", "content": "c"},
                        {"tag": "2", "content": "rdamedia"},
                    ],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "338",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "online resource"},
                        {"tag": "b", "content": "cr"},
                        {"tag": "2", "content": "rdacarrier"},
                    ],
                },
                {
                    "fieldTag": "t",
                    "marcTag": "245",
                    "ind1": "1",
                    "ind2": "4",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "The saddest words"},
                        {"tag": "h", "content": "[electronic resource] :"},
                        {"tag": "b", "content": "William faulkner's civil war."},
                        {"tag": "c", "content": "Michael Gorra."},
                    ],
                },
                {
                    "fieldTag": "w",
                    "marcTag": "776",
                    "ind1": "1",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "c", "content": "Original"},
                        {"tag": "z", "content": "9781631491702"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "006",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "m        d        ",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "007",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "cr cn---------",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "008",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "200502s2020    nyu     s     000 0 eng dnamKa ",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "037",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "40CC3B3F-4C30-4685-B391-DB7B2EA91455"},
                        {"tag": "b", "content": "OverDrive, Inc."},
                        {"tag": "n", "content": "http://www.overdrive.com"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "040",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "TEFOD"},
                        {"tag": "c", "content": "TEFOD"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "084",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "BIO007000"},
                        {"tag": "a", "content": "HIS036050"},
                        {"tag": "a", "content": "LIT004020"},
                        {"tag": "2", "content": "bisacsh"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": "0",
                    "content": None,
                    "subfields": [
                        {
                            "tag": "u",
                            "content": "http://link.overdrive.com/?content",
                        },
                        {"tag": "z", "content": "Access eNYPL"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Excerpt"},
                        {
                            "tag": "u",
                            "content": "https://samples.overdrive.com/?sample_url",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Image"},
                        {
                            "tag": "u",
                            "content": "https://img1.od-cdn.com/ImageType-100/image.jpg",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Thumbnail"},
                        {
                            "tag": "u",
                            "content": "https://img1.od-cdn.com/ImageType-200/thumbnail.jpg",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "901",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "OverDrive_ME-0837"}],
                },
                {
                    "fieldTag": "_",
                    "marcTag": None,
                    "ind1": None,
                    "ind2": None,
                    "content": "00000nam a2200385Ka 4500",
                    "subfields": None,
                },
            ],
        },
        {
            "id": "22259003",
            "nyplSource": "sierra-nypl",
            "nyplType": "bib",
            "updatedDate": "2020-09-22T20:23:19-04:00",
            "createdDate": "2020-09-22T20:23:19-04:00",
            "deletedDate": None,
            "deleted": False,
            "locations": [{"code": "ia", "name": "Electronic Material for Adults"}],
            "suppressed": False,
            "lang": {"code": "eng", "name": "English"},
            "title": "Passion of the western mind [electronic resource] : Understanding the ideas that have shaped our world view.",
            "author": "Tarnas, Richard.",
            "materialType": {"code": "z  ", "value": "E-BOOK"},
            "bibLevel": {"code": "m", "value": "MONOGRAPH"},
            "publishYear": 2011,
            "catalogDate": "2020-09-22",
            "country": {"code": "nyu", "name": "New York (State)"},
            "normTitle": "passion of the western mind electronic resource understanding the ideas that have shaped our world view",
            "normAuthor": "tarnas richard",
            "standardNumbers": ["9780307804525"],
            "controlNumber": "ODN0000647341",
            "fixedFields": {
                "24": {"label": "Language", "value": "eng", "display": "English"},
                "25": {"label": "Skip", "value": "0", "display": None},
                "26": {
                    "label": "Location",
                    "value": "ia   ",
                    "display": "Electronic Material for Adults",
                },
                "27": {"label": "COPIES", "value": "1", "display": None},
                "28": {"label": "Cat. Date", "value": "2020-09-22", "display": None},
                "29": {"label": "Bib Level", "value": "m", "display": "MONOGRAPH"},
                "30": {"label": "Material Type", "value": "z  ", "display": "E-BOOK"},
                "31": {"label": "Bib Code 3", "value": "a", "display": None},
                "80": {"label": "Record Type", "value": "b", "display": None},
                "81": {"label": "Record Number", "value": "22259003", "display": None},
                "83": {
                    "label": "Created Date",
                    "value": "2020-09-22T20:23:19Z",
                    "display": None,
                },
                "84": {
                    "label": "Updated Date",
                    "value": "2020-09-22T20:23:19Z",
                    "display": None,
                },
                "85": {"label": "No. of Revisions", "value": "1", "display": None},
                "86": {"label": "Agency", "value": "1", "display": None},
                "89": {
                    "label": "Country",
                    "value": "nyu",
                    "display": "New York (State)",
                },
                "98": {
                    "label": "PDATE",
                    "value": "2020-09-22T20:23:19Z",
                    "display": None,
                },
                "107": {"label": "MARC Type", "value": " ", "display": None},
            },
            "varFields": [
                {
                    "fieldTag": "a",
                    "marcTag": "100",
                    "ind1": "1",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "Tarnas, Richard."}],
                },
                {
                    "fieldTag": "b",
                    "marcTag": "710",
                    "ind1": "2",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "OverDrive, Inc.,"},
                        {"tag": "e", "content": "distributor."},
                    ],
                },
                {
                    "fieldTag": "c",
                    "marcTag": "091",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "eNYPL Book"}],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "650",
                    "ind1": " ",
                    "ind2": "7",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Philosophy."},
                        {"tag": "2", "content": "OverDrive"},
                    ],
                },
                {
                    "fieldTag": "d",
                    "marcTag": "655",
                    "ind1": " ",
                    "ind2": "0",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "Electronic books."}],
                },
                {
                    "fieldTag": "i",
                    "marcTag": "020",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "9780307804525"},
                        {"tag": "q", "content": "(electronic bk)"},
                    ],
                },
                {
                    "fieldTag": "n",
                    "marcTag": "520",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {
                            "tag": "a",
                            "content": "\"[This] magnificent critical survey, with its inherent respect for both the 'Westt's mainstream high culture' and the 'radically changing world' of the 1990s, offers a new breakthrough for lay and scholarly readers alike....Allows readers to grasp the big picture of Western culture for the first time.\" SAN FRANCISCO CHRONICLE Here are the great minds of Western civilization and their pivotal ideas, from Plato to Hegel, from Augustine to Nietzsche, from Copernicus to Freud. Richard Tarnas performs the near-miracle of describing profound philosophical concepts simply but without simplifying them. Ten years in the making and already hailed as a classic, THE PASSION OF THE WESERN MIND is truly a complete liberal education in a single volume. From the Trade Paperback edition.",
                        }
                    ],
                },
                {
                    "fieldTag": "n",
                    "marcTag": "533",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Electronic reproduction."},
                        {"tag": "b", "content": "New York :"},
                        {"tag": "c", "content": "Ballantine Books,"},
                        {"tag": "d", "content": "2011."},
                        {
                            "tag": "n",
                            "content": "Requires OverDrive Read (file size: N/A KB) or Adobe Digital Editions (file size: 2290 KB) or Kobo app or compatible Kobo device (file size: N/A KB) or Amazon Kindle (file size: N/A KB).",
                        },
                    ],
                },
                {
                    "fieldTag": "o",
                    "marcTag": "001",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "ODN0000647341",
                    "subfields": None,
                },
                {
                    "fieldTag": "p",
                    "marcTag": "260",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "c", "content": "2011."}],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "300",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "1 online resource"}],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "336",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "text"},
                        {"tag": "b", "content": "txt"},
                        {"tag": "2", "content": "rdacontent"},
                    ],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "337",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "computer"},
                        {"tag": "b", "content": "c"},
                        {"tag": "2", "content": "rdamedia"},
                    ],
                },
                {
                    "fieldTag": "r",
                    "marcTag": "338",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "online resource"},
                        {"tag": "b", "content": "cr"},
                        {"tag": "2", "content": "rdacarrier"},
                    ],
                },
                {
                    "fieldTag": "t",
                    "marcTag": "245",
                    "ind1": "1",
                    "ind2": "0",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "Passion of the western mind"},
                        {"tag": "h", "content": "[electronic resource] :"},
                        {
                            "tag": "b",
                            "content": "Understanding the ideas that have shaped our world view.",
                        },
                        {"tag": "c", "content": "Richard Tarnas."},
                    ],
                },
                {
                    "fieldTag": "w",
                    "marcTag": "776",
                    "ind1": "1",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "c", "content": "Original"},
                        {"tag": "z", "content": "9780345368096"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "006",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "m        d        ",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "007",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "cr cn---------",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "008",
                    "ind1": " ",
                    "ind2": " ",
                    "content": "171212s2011    nyu     s     000 0 eng dnamKa ",
                    "subfields": None,
                },
                {
                    "fieldTag": "y",
                    "marcTag": "037",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "4E7547BF-6D42-43F4-9180-8FCF302497F3"},
                        {"tag": "b", "content": "OverDrive, Inc."},
                        {"tag": "n", "content": "http://www.overdrive.com"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "040",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "TEFOD"},
                        {"tag": "c", "content": "TEFOD"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "084",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "a", "content": "PHI004000"},
                        {"tag": "a", "content": "PHI005000"},
                        {"tag": "a", "content": "PHI021000"},
                        {"tag": "2", "content": "bisacsh"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": "0",
                    "content": None,
                    "subfields": [
                        {
                            "tag": "u",
                            "content": "http://link.overdrive.com/?websiteID=37&titleID=647341",
                        },
                        {"tag": "z", "content": "Access eNYPL"},
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Excerpt"},
                        {
                            "tag": "u",
                            "content": "https://samples.overdrive.com/?crid=4E7547BF-6D42-43F4-9180-8FCF302497F3&.epub-sample.overdrive.com",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Image"},
                        {
                            "tag": "u",
                            "content": "https://img1.od-cdn.com/ImageType-100/0111-1/%7B4E7547BF-6D42-43F4-9180-8FCF302497F3%7DImg100.jpg",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "856",
                    "ind1": "4",
                    "ind2": " ",
                    "content": None,
                    "subfields": [
                        {"tag": "3", "content": "Thumbnail"},
                        {
                            "tag": "u",
                            "content": "https://img1.od-cdn.com/ImageType-200/0111-1/%7B4E7547BF-6D42-43F4-9180-8FCF302497F3%7DImg200.jpg",
                        },
                    ],
                },
                {
                    "fieldTag": "y",
                    "marcTag": "901",
                    "ind1": " ",
                    "ind2": " ",
                    "content": None,
                    "subfields": [{"tag": "a", "content": "OverDrive_ME-0837"}],
                },
                {
                    "fieldTag": "_",
                    "marcTag": None,
                    "ind1": None,
                    "ind2": None,
                    "content": "00000nam a2200361Ka 4500",
                    "subfields": None,
                },
            ],
        },
        {
            "id": "19099433",
            "nyplSource": "sierra-nypl",
            "nyplType": "bib",
            "updatedDate": None,
            "createdDate": "2017-08-23T17:59:35-04:00",
            "deletedDate": "2011-09-15",
            "deleted": True,
            "locations": [],
            "suppressed": None,
            "lang": None,
            "title": None,
            "author": None,
            "materialType": None,
            "bibLevel": None,
            "publishYear": None,
            "catalogDate": None,
            "country": None,
            "normTitle": None,
            "normAuthor": None,
            "standardNumbers": [],
            "controlNumber": "",
            "fixedFields": [],
            "varFields": [],
        },
    ],
    "count": 5,
    "totalCount": 0,
    "statusCode": 200,
    "debugInfo": [],
}
