name: tests
on: 
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ns_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 5432:5432
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]    
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install Poetry with pipx
        run: pipx install poetry

      - name: Install dependencies with poetry
        run: poetry install --no-root  

      - name: Run tests
        run: poetry run pytest -m "not firewalled and not local" --cov=nightshift/ --cov-report=xml
        
      - name: Send report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          github-token: ${{ secrets.GITHUB_TOKEN}}
          flag-name: ${{ matrix.python-version}}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true